version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - printenv
      - apt-get update -y
      - nvm --version
    finally:
      - echo This always runs even if the update or install command fails